# @see /usr/share/portage/config/make.conf.example
# Also, the make.conf can be a directory as well, but seems unneccessary.

# Flags:
COMMON_FLAGS="-O2 -pipe{% if os.hostname == "evil" %} -march=znver4{% endif %}"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
CCACHE_DIR="/var/cache/ccache"
GENTOO_MIRRORS="https://mirrors.ustc.edu.cn/gentoo/ https://mirrors.cqu.edu.cn/gentoo-zh/"

# Locale:
LC_MESSAGES=C.utf8
L10N="zh-CN"
USE="${USE} cjk"

# Binary packages:
USE="${USE} bindist"
FEATURES="${FEATURES} getbinpkg binpkg-request-signature"

# Hardware:
{% if os.hostname == "evil" %}
VIDEO_CARDS="amdgpu radeonsi"
USE="${USE} -bluetooth"
{% endif %}

# Kernel:
USE="${USE} dist-kernel -initramfs"

# Desktop:
USE="${USE} -gnome-online-accounts"
